### ISSUE TITLE
Missing functionality: ensure_installed

### ISSUE THREAD

**Issue by plague-doctor** [Zeioth/none-ls-autoload.nvim#1]
If only this plugin had "ensure_installed" (the same as mason-null-ls) it would be perfect.
Any chance you could include it?

**Comment by Zeioth** [comment]
@plague-doctor Unless I'm wrong, it would make more sense to implement that on mason itself. Maybe I could add that feature to https://github.com/Zeioth/mason-extra-cmds, or to a new plugin.

Give me some time to study it.

**Comment by Zeioth** [comment]
Another posibility if mason-null-ls support external sources: https://github.com/jay-babu/mason-null-ls.nvim/issues/106

**Comment by Zeioth** [comment]
Just to clarify: I can't work on this rn, but I'm willing to review PR.
